# Generated by Django 6.0 on 2025-12-16 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enor_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='main_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Editor', 'Editor'), ('Admin', 'Admin')], default='Customer', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Banned', 'Banned')], default='Inactive', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=255)),
                ('building_number', models.CharField(blank=True, max_length=50)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('apartment_number', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(choices=[('CAI', 'Cairo'), ('ALX', 'Alexandria'), ('GZ', 'Giza'), ('SHR', 'Sharqia'), ('KB', 'Qalyubia'), ('MNF', 'Minya'), ('WAD', 'New Valley'), ('SIN', 'North Sinai'), ('SHG', 'South Sinai'), ('BNS', 'Beni Suef'), ('FSH', 'Faiyum'), ('GH', 'Gharbia'), ('IS', 'Ismailia'), ('KFS', 'Kafr El Sheikh'), ('LX', 'Luxor'), ('MT', 'Matrouh'), ('MN', 'Monufia'), ('PTS', 'Port Said'), ('SUZ', 'Suez'), ('SHW', 'Sohag'), ('ASW', 'Aswan'), ('AST', 'Asyut'), ('DBY', 'Damietta'), ('BHR', 'Beheira'), ('DGH', 'Dakahlia'), ('RED', 'Red Sea'), ('QEN', 'Qena')], default='Cairo', max_length=100)),
                ('address_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
