# Generated by Django 6.0 on 2025-12-19 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enor_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='image',
        ),
    ]
