# Generated by Django 6.0 on 2025-12-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enor_store', '0002_remove_color_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
