# Generated by Django 6.0 on 2026-06-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enor_content', '0002_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_links',
            name='icon',
            field=models.CharField(max_length=255),
        ),
    ]
