# Generated by Django 6.0 on 2026-06-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enor_content', '0004_alter_social_links_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_links',
            name='icon',
            field=models.TextField(),
        ),
    ]
