"""
Django settings for enor_core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os

from pathlib import Path
import environ 
import dj_database_url

env = environ.Env()
environ.Env.read_env()
ENVIRONMENT=env('ENVIRONMENT', default='production')
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
if ENVIRONMENT == 'development':
    DEBUG = True
else:
    DEBUG = False

if ENVIRONMENT == 'development':
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = ['*']

INTERNAL_IPS = [
"*"
]
# Application definition


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'django.contrib.sites',  # ← Required for allauth
    # Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.apple',
    
    'widget_tweaks', # for form styling
    #my apps
    'category',
    'enor_profile',
    'enor_store',
    'enor_cart',
    'enor_order',
    'enor_admin',
    'enor_content',

]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.security.csrf': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #all auth mw
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'enor_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'enor_cart.context_processors.cart_count',
                'enor_store.context_processors.products_processor',
                'enor_store.context_processors.categories_processor',
                'enor_content.context_processors.social_links_processor',
                'enor_content.context_processors.contact_info_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'enor_core.wsgi.application'

# ===== ALLAUTH CONFIG =====
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

# Site ID (required)
SITE_ID = 1

# Email (for account verification, etc.)
# ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
# ACCOUNT_EMAIL_VERIFICATION = 'optional'  # or 'optional'
ACCOUNT_LOGIN_METHODS = {'email'}
# ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True  # auto-login after confirm
# ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True

LOGIN_REDIRECT_URL = '/'          # after login
LOGOUT_REDIRECT_URL = '/'         # after logout
ACCOUNT_LOGOUT_ON_GET = True      # for ease (or set to False for confirmation)
SOCIALACCOUNT_LOGIN_ON_GET = True  # auto login after social signup

# Password reset
# PASSWORD_RESET_TIMEOUT = 259200   # 1 hour (default: 3 days)

ACCOUNT_LOGIN_ON_PASSWORD_RESET = True  # auto-login after reset
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

# Prevent signups from non-social login (optional)
# ACCOUNT_ADAPTER = 'shop.adapters.NoPasswordSignupAdapter'

# Custom form styling (optional — see templates below)
ACCOUNT_FORMS = {
    'signup': 'allauth.account.forms.SignupForm',
    'login': 'allauth.account.forms.LoginForm',
}
# Apple Sign In
SOCIALACCOUNT_PROVIDERS = {
    # 'apple': {
    #     'APP': {
    #         'client_id': 'com.boost.signin',        # Services ID
    #         'secret': '-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwE...-----END PRIVATE KEY-----',
    #         'key_id': 'ABC123DEFG',
    #         'team_id': 'TEAM9876543',
    #     },
    #     'SCOPE': ['email', 'name'],  # Apple only sends name/email on first login
    #     'AUTH_PARAMS': {'access_type': 'offline'},
    # },
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'EMAIL_AUTHENTICATION': True,
    }
}
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATA_UPLOAD_MAX_MEMORY_SIZE = 26214400  # 25 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 15728640   # 15 MB

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
POSTGRES_LOCALLY = True

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


if ENVIRONMENT == 'production' or POSTGRES_LOCALLY == True:
    DATABASES['default'] = dj_database_url.parse(env('DATABASE_URL'))


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True

# EMAIL_HOST_USER = 'Enorfitness1@gmail.com'
# EMAIL_HOST_PASSWORD = 'your_app_password'  # NOT your normal password

# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

EMAIL_BACKEND = "enor_core.resend_backend.ResendBackend"

DEFAULT_FROM_EMAIL = "noreply@enorfitness.com"

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
if ENVIRONMENT == 'production' or POSTGRES_LOCALLY == True:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
        },
        "staticfiles" :{
            "BACKEND":"django.contrib.staticfiles.storage.StaticFilesStorage"
        }
    }
    AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = env('AWS_ACCESS_SECRET_KEY')
    AWS_STORAGE_BUCKET_NAME = env('AWS_BUCKET_NAME')
    # 1. Explicitly set the correct region for your bucket
    AWS_S3_REGION_NAME = 'us-east-1' 
    
    # 2. Force Django to use Signature Version 4
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    # AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME', default='us-east-1')
    
    # Tell Django to use S3 for Media Files
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    # MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/media/'
    # AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    # AWS_QUERYSTRING_AUTH = False
    
else:
    MEDIA_ROOT = BASE_DIR / 'media'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [ BASE_DIR / 'static' ]
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'