# Generated by Django 6.0 on 2025-12-19 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enor_order', '0001_initial'),
        ('enor_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enor_store.productitem'),
        ),
    ]
