# Generated by Django 6.0 on 2025-12-23 17:25

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enor_order', '0003_voucher_remove_order_user_remove_orderitem_order_and_more'),
        ('enor_profile', '0002_userprofile_main_phone_userprofile_role_and_more'),
        ('enor_store', '0004_product_before_price_productreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('deliverd', 'Deliverd'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('paymment_method', models.CharField(default='cod', max_length=50)),
                ('instapay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('addresss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enor_profile.useraddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enor_order.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='enor_order.order')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enor_store.productitem')),
            ],
        ),
    ]
