# Generated by Django 6.0 on 2025-12-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enor_order', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='addresss',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paymment_method',
            new_name='payment_method',
        ),
    ]
